---
namespace: lazyninjas
name: gcp
version: 0.5.0
readme: README.md
authors:
  - Pavel Žák <pavel@zak.global>
description: A tiny set of Ansible roles that will help you live on \
  the Google Cloud Platform
license: GPL-3.0-or-later
repository: https://github.com/lazyninjas/gcp
documentation: https://github.com/lazyninjas/gcp
issues: https://github.com/lazyninjas/gcp/issues
tags:
  - gcp
  - google
  - cloud
  - platform
  - storage
  - bucket
  - function
  - api
  - service
build_ignore:
  - .github
  - tools
dependencies:
  "google.cloud": "1.0.2"
