---
- name: 'Create GCP Bucket: {{ bucket.name }}'
  google.cloud.gcp_storage_bucket:
    auth_kind: serviceaccount
    location: '{{ bucket.region | default(gcp_region, true) }}'
    name: '{{ bucket.name }}'
    project: '{{ gcp_project_id }}'
    service_account_file: '{{ gcp_service_account_file }}'
    state: '{{ state }}'
    storage_class: '{{ bucket.storage_class | default("STANDARD", true) }}'
  register: bucket_inst

- name: 'Make {{ bucket.name }} uniform bucket level access'
  ansible.builtin.shell: gsutil ubla set on gs://{{ dest_bucket }}

- name: 'Make {{ bucket.name }} public'
  ansible.builtin.shell: gsutil iam ch allUsers:objectViewer gs://{{ dest_bucket }}
  when: public
