---
- name: 'Create GCP Bucket: {{ bucket.name }}'
  google.cloud.gcp_storage_bucket:
    auth_kind: serviceaccount
    location: '{{ bucket.region | default(gcp_region, true) }}'
    name: '{{ bucket.name }}'
    project: '{{ gcp_project_id }}'
    service_account_file: '{{ gcp_service_account_file }}'
    state: '{{ state }}'
    storage_class: '{{ bucket.storage_class | default("STANDARD", true) }}'

- name: 'Make {{ bucket.name }} public'
  google.cloud.gcp_storage_bucket_access_control:
    auth_kind: serviceaccount
    bucket: '{{ bucket.name }}'
    entity: allUsers
    project: '{{ gcp_project_id }}'
    role: READER
    service_account_file: '{{ gcp_service_account_file }}'
    state: '{{ state }}'
