---
galaxy_info:
  author: Pavel Žák <pavel@zak.global>
  role_name: gcp_function
  license: GPL-3.0-or-later
  min_ansible_version: 2.9
  description: Deploy Gooogle Cloud Functions with Ansible
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - gcp
    - google
    - cloud
    - platform
    - storage
    - bucket

allow_duplicates: true
dependencies:
  - role: gcp_api
    apis:
      - cloudfunctions.googleapis.com
      - cloudbuild.googleapis.com
  - role: gcp_bucket
    buckets:
      - name: '{{ resource_bucket }}'
