---
galaxy_info:
  author: Pavel Žák <pavel@zak.global>
  role_name: gcp_api
  license: GPL-3.0-or-later
  min_ansible_version: 2.9
  description: Enable GCP services from Ansible.
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - gcp
    - google
    - cloud
    - platform
    - api
    - service

allow_duplicates: true
dependencies:
  - gcp_env
