---
- name: 'Upload Function {{ func.name }} artifact'
  lazyninjas.gcp.gc_storage_object:
    action: upload
    auth_kind: serviceaccount
    bucket: '{{ resource_bucket }}'
    dest: '{{ func.artifact_bucket_path }}'
    project: '{{ gcp_project_id }}'
    service_account_file: '{{ gcp_service_account_file }}'
    src: '{{ func.artifact_path }}'
  when: state == 'present'

- name: 'Deploy Function {{ func.name }}'
  lazyninjas.gcp.gc_cloudfunctions_cloud_function:
    auth_kind: serviceaccount
    available_memory_mb: '{{ func.memory_mb | default(omit) }}'
    description: '{{ func.description | default(omit) }}'
    entry_point: '{{ func.entry_point }}'
    environment_variables: '{{ func.env_vars | default(env_vars) }}'
    event_trigger: '{{ func.event_trigger | default(omit) }}'
    location: '{{ func.region | default(gcp_region, true) }}'
    max_instances: '{{ func.max_instances | default(omit) }}'
    name: '{{ func.name }}'
    project: '{{ gcp_project_id }}'
    runtime: '{{ func.runtime | default("nodejs14", true) }}'
    service_account_file: '{{ gcp_service_account_file }}'
    service_account_email: '{{ runtime_account | default(omit) }}'
    source_archive_url: 'gs://{{ resource_bucket }}/{{ func.artifact_bucket_path }}'
    state: '{{ func.state | default(state, true) }}'
    timeout: '{{ func.timeout | default(omit) }}'
    trigger_http: '{{ func.trigger_http | default(omit) }}'
