---
- name: 'Enable GCP APIs'
  google.cloud.gcp_serviceusage_service:
    auth_kind: serviceaccount
    name: '{{ item }}'
    project: '{{ gcp_project_id }}'
    service_account_file: '{{ gcp_service_account_file }}'
    state: '{{ state }}'
  loop: '{{ apis }}'
