---
galaxy_info:
  author: Pavel Žák <pavel@zak.global>
  role_name: gcp_env
  license: GPL-3.0-or-later
  min_ansible_version: 2.9
  description: Parent of practical gcp collection roles. Not intended for \
    standalone use.
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

allow_duplicates: true
