---
galaxy_info:
  author: Pavel Žák <pavel@zak.global>
  role_name: gcp_shell_account
  license: GPL-3.0-or-later
  min_ansible_version: 2.9
  description: Configure gcloud shell account
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - gcp
    - google
    - cloud
    - platform
    - shell

allow_duplicates: true
dependencies:
  - role: lazyninjas.gcp.gcp_env
