---
name: Integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  lint:
    name: Lint the package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-lint-action@master
        with:
          args: -c .ansible-lint
